# contains values that are common for both executors

# secret my-aws-connection must be created before installing airflow
#secret:
#  - envName: "AIRFLOW_CONN_MY_AWS_CONNECTION"
#    secretName: "my-aws-connection"
#    secretKey: "AIRFLOW_CONN_MY_AWS_CONNECTION"

# pvc my-existing-pvc must be created before installing airflow
volumes:
- name: my-volume
  persistentVolumeClaim:
    claimName: my-existing-pvc
# VolumeMounts for all airflow containers
volumeMounts:
- name: my-volume
  mountPath: "/usr/local/tmp"

workers:
  # Number of airflow celery_executor workers in StatefulSet
  replicas: 1

dags:
  persistence:
    enabled: false

  gitSync:
    enabled: true
    repo: https://github.com/filipio/apache-airflow-mlops.git
    branch: master
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"