# contains values that are common for both executors

# secret my-aws-connection must be created before installing airflow
secret:
  - envName: "AWS_ACCESS_KEY_ID"
    secretName: "my-aws-connection"
    secretKey: "AWS_ACCESS_KEY_ID"
  - envName: "AWS_SECRET_ACCESS_KEY"
    secretName: "my-aws-connection"
    secretKey: "AWS_SECRET_ACCESS_KEY"
  - envName: "AWS_SESSION_TOKEN"
    secretName: "my-aws-connection"
    secretKey: "AWS_SESSION_TOKEN"

images:
  airflow:
    repository: "my-dags"
    tag: "0.0.1"

# pvc my-existing-pvc must be created before installing airflow
volumes:
- name: my-volume
  persistentVolumeClaim:
    claimName: my-existing-pvc
# VolumeMounts for all airflow containers
volumeMounts:
- name: my-volume
  mountPath: "/mnt/shared"

dags:
  persistence:
    enabled: false

  gitSync:
    enabled: true
    repo: https://github.com/filipio/apache-airflow-mlops.git
    branch: master
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"